parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single
  no-unused-vars:
    - error
    - vars: all
  no-undef:
    - error
env:
  node: true
