export const TRIGGER_SPOILER = "TRIGGER_SPOILER";
export const EXPAND_ARTICLE = "EXPAND_ARTICLE";
export const FETCH_PARAGRAPHS = "FETCH_PARAGRAPHS";

export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const FETCH_ARTICLES = "FETCH_ARTICLES";

export const CHANGE_DATE = "CHANGE_DATE";